name: Build and publish to github repo

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: peterhs73/sphinx-docs-action@v0.0.2
        with:
          docs-source: docs/
          external-repo: peterhs73/mmodel-docs
          deploy-token: ${{ secrets.PRIVATE_TOKEN}}
