name: Build and publish to github repo

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: peterhs73/sphinx-docs-action@v0.2.1
        with:
          python-version: "3.10"
          docs-source: docs/
          pyproject-path: .[docs]
          external-repo: Marohn-Group/mmodel-docs
          deploy-token: ${{ secrets.PRIVATE_TOKEN}}
