name: Build and publish to github repo

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: peterhs73/sphinx-docs-action@v0.1.0
        with:
          docs-source: docs/
          dependency-path: tool.poetry.dependencies
          external-repo: Marohn-Group/mmodel-docs
          deploy-token: ${{ secrets.PRIVATE_TOKEN}}
